# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20170605_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_bills',
            new_name='Add_bill',
        ),
    ]
