# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0004_auto_20170605_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess_member',
            name='member',
        ),
        migrations.AddField(
            model_name='mess_member',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
