# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_auto_20170605_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess_member',
            old_name='invest',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='mess_member',
            name='total',
        ),
    ]
