# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_auto_20170615_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='amount',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.AddField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(default=datetime.datetime(2017, 6, 17, 5, 38, 31, 519843, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
