# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_auto_20170617_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(default=datetime.datetime(2017, 6, 17, 6, 48, 38, 924567, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
