# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_member_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.AddField(
            model_name='wsgroup',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
