# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_auto_20170617_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsgroup',
            name='group_members',
            field=models.ManyToManyField(to='mess.Member'),
        ),
    ]
