# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 08:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0013_auto_20170617_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 20, 8, 46, 1, 311680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
